all: punto1 punto2 punto3 punto4 punto5 punto6

punto1: punto1.c
	gcc punto1.c -o punto1

punto2: punto2.c
	gcc punto2.c -o punto2

punto3: punto3.c
	gcc punto3.c -o punto3

punto4: punto4.c
	gcc punto4.c -o punto4

punto5: punto5.c
	gcc punto5.c -o punto5